[project]
name = "validation-tool-py"
requires-python = "==3.12.11"
version = "0.1.0"
dependencies = [
    "Flask",
    "Pillow",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["validation_tool"]
