openapi: 3.0.0
info:
  title: Diary Archival Schema
  version: 1.0.0
  description: A schema for extracting and structuring information from scanned diary pages for an archival project.
paths: {}
components:
  schemas:
    Diary:
      type: object
      description: Represents a single, complete diary document.
      properties:
        metadata:
          $ref: '#/components/schemas/DiaryMetadata'
        people_index:
          type: array
          description: A comprehensive index of all individuals mentioned in the diary.
          items:
            $ref: '#/components/schemas/Person'
        entries:
          type: array
          description: A chronological list of all the entries transcribed from the diary.
          items:
            $ref: '#/components/schemas/DiaryEntry'
      required:
        - metadata
        - people_index
        - entries

    DiaryMetadata:
      type: object
      description: Metadata about the physical diary itself.
      properties:
        archive_id:
          type: string
          description: The unique identifier for this diary in the archival system.
          example: "D-1895-JHS-001"
        title:
          type: string
          description: The title of the diary, if one is written on the cover (e.g., "My European Tour"). Otherwise, a generated title.
          example: "Journal of John H. Smith, 1895"
        author:
          type: string
          description: The name of the person who wrote the diary. Can be "Unknown".
          example: "John H. Smith"
        date_range:
          type: object
          properties:
            start_date:
              type: string
              format: date
              description: The ISO 8601 date of the first entry.
              example: "1895-01-01"
            end_date:
              type: string
              format: date
              description: The ISO 8601 date of the last entry.
              example: "1895-12-31"
        physical_description:
          type: string
          description: A description of the physical object (e.g., "Small leather-bound book, brown cover with gold leaf, spine is damaged, 150 pages.")
          example: "Brown leather-bound diary, 5x7 inches, with significant water damage on the back cover."
        provenance:
          type: string
          description: Information about the diary's origin and ownership history.
          example: "Donated by the estate of Eleanor Vance, granddaughter of the author."
        language:
          type: string
          description: The primary language of the diary.
          example: "English"
        key_entities:
          type: array
          description: A list of significant recurring organizations, groups, or concepts mentioned in the diary.
          items:
            type: object
            properties:
              name:
                type: string
                example: "Arcadettes"
              type:
                type: string
                enum: [Organization, Club, Publication, Event, Other]
                example: "Club"
              description:
                type: string
                example: "A social club the author and her friends (like Lilly and Dody) are members of."

    Person:
      type: object
      description: An entry for a single person mentioned in the diary.
      properties:
        person_id:
          type: string
          description: A unique, internally generated ID for this person (e.g., 'person-001'). Useful for linking.
        name:
          type: string
          description: The full name of the person. Standardize where possible (e.g., "Robert" instead of "Rob").
          example: "Eleanor Vance"
        aliases:
          type: array
          description: A list of other names or initials this person is referred to by in the text.
          items:
            type: string
          example: ["Lilly"]
        category:
          type: string
          description: The general category of the person.
          enum: [Family, Friend, Classmate, Teacher, Public Figure, Acquaintance, Organization Member, Unknown]
          example: "Friend"
        is_primary_author:
          type: boolean
          description: "True if this person is the author of the diary."
          example: false
        relationship_to_author:
          type: string
          description: Inferred relationship to the diary's author (e.g., Sister, Father, Business Partner, Friend).
          example: "Neighbor"
        description:
          type: string
          description: A brief, generated summary of this person based on all mentions in the diary.
          example: "A close friend of the author, frequently mentioned in social contexts and as a confidante."
        mention_count:
          type: integer
          description: The total number of entries this person is mentioned in.
          example: 14

    DiaryEntry:
      type: object
      description: Represents a single entry within the diary.
      properties:
        date_info:
          $ref: '#/components/schemas/DateInfo'
        page_number:
          type: integer
          description: The page number where this entry begins.
          example: 42
        full_text:
          type: string
          description: The complete, verbatim transcription of the diary entry.
          example: "A dreary day. The rain has not ceased for a moment. Had tea with Eleanor Vance this afternoon. She is worried about her brother Robert's cough. We spoke of the upcoming town fair and whether we should attend."
        summary:
          type: string
          description: A one or two-sentence summary of the entry's content.
          example: "The author describes a rainy day and having tea with Eleanor Vance, discussing her brother's illness and the town fair."
        mentioned_people:
          type: array
          description: A list of people mentioned specifically in this entry.
          items:
            $ref: '#/components/schemas/Mention'
        mentioned_locations:
          type: array
          description: A list of specific places mentioned in this entry (e.g., "Miller's Pond", "London", "The Grand Hotel").
          items:
            type: string
          example: ["Town Fair"]
        key_events:
          type: array
          description: A list of key events or topics discussed in the entry.
          items:
            type: string
          example: ["Tea with Eleanor", "Robert's illness"]
        sentiment:
          type: string
          description: The inferred overall sentiment of the entry.
          enum: [Positive, Negative, Neutral, Mixed]
          example: "Negative"
        annotations:
          type: array
          description: A list of noteworthy cultural references, slang, or ambiguous terms with explanations.
          items:
            type: object
            properties:
              term:
                type: string
                example: "sharpies"
              context:
                type: string
                example: "There sharpies while we're serious girls."
              explanation:
                type: string
                example: "A 1940s slang term for individuals (often girls) who were perceived as flashy, stylish, and possibly rebellious or of a lower social class."

    DateInfo:
      type: object
      description: Detailed information about the date of an entry, handling ambiguity.
      properties:
        original_text:
          type: string
          description: The date as it was originally written in the diary.
          example: "Tuesday, the 15th of March"
        iso_date:
          type: string
          format: date
          description: The normalized date in YYYY-MM-DD format. Null if it cannot be determined.
          example: "1895-03-15"
        date_confidence:
          type: string
          description: Confidence level in the accuracy of the normalized ISO date.
          enum: [High, Medium, Low, Inferred]
          example: "High"

    Mention:
      type: object
      description: Details of a single mention of a person within an entry.
      properties:
        name:
          type: string
          description: The name of the person as it appears in the text.
          example: "Eleanor Vance"
        context:
          type: string
          description: The specific phrase or sentence where the person was mentioned, providing context.
          example: "Had tea with Eleanor Vance this afternoon."